# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GameMeta.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import QuestionsMeta_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='GameMeta.proto',
  package='',
  serialized_pb='\n\x0eGameMeta.proto\x1a\x13QuestionsMeta.proto\"B\n\x08GameMeta\x12\x0f\n\x07metaVer\x18\x01 \x02(\x03\x12%\n\rquestionsMeta\x18\x03 \x03(\x0b\x32\x0e.QuestionsMeta')




_GAMEMETA = _descriptor.Descriptor(
  name='GameMeta',
  full_name='GameMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metaVer', full_name='GameMeta.metaVer', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='questionsMeta', full_name='GameMeta.questionsMeta', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=105,
)

_GAMEMETA.fields_by_name['questionsMeta'].message_type = QuestionsMeta_pb2._QUESTIONSMETA
DESCRIPTOR.message_types_by_name['GameMeta'] = _GAMEMETA

class GameMeta(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAMEMETA

  # @@protoc_insertion_point(class_scope:GameMeta)


# @@protoc_insertion_point(module_scope)
