# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QuestionsMeta.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='QuestionsMeta.proto',
  package='',
  serialized_pb='\n\x13QuestionsMeta.proto\"Q\n\rQuestionsMeta\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x12\n\ndifficulty\x18\x02 \x02(\x05\x12\x10\n\x08question\x18\x03 \x02(\t\x12\x0e\n\x06\x61nswer\x18\x04 \x02(\x08')




_QUESTIONSMETA = _descriptor.Descriptor(
  name='QuestionsMeta',
  full_name='QuestionsMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='QuestionsMeta.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='difficulty', full_name='QuestionsMeta.difficulty', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='question', full_name='QuestionsMeta.question', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='answer', full_name='QuestionsMeta.answer', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['QuestionsMeta'] = _QUESTIONSMETA

class QuestionsMeta(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUESTIONSMETA

  # @@protoc_insertion_point(class_scope:QuestionsMeta)


# @@protoc_insertion_point(module_scope)
